### PR TITLE
Minor fixes

### LINKED ISSUE #73: Return pointers instead of values in many places in backend code

### PR DESCRIPTION
**Pull request by Prytu**
Few minor fixes.
Also closes #73

### CODE REVIEW

File: backend/services/services.go [hunk 1]
```diff
@@ -51,42 +51,42 @@ func GetTweetsOfUserWithID(userID int64) ([]APIModel.Tweet, *appErrors.AppError)
...
 }
 
-func GetTweet(tweetID int64) (APIModel.Tweet, *appErrors.AppError) {
+func GetTweet(tweetID int64) (*APIModel.Tweet, *appErrors.AppError) {
 	databaseTweet, databaseError := database.GetTweet(tweetID)
 
 	if databaseError != nil {
 		// Later on we'll need to add type switch here to check the type of error, because several things
 		// can go wrong when fetching data from database: not found, SQL error, db connection error etc
-		return APIModel.Tweet{}, &appErrors.AppError{
```
Comment (VirrageS) [inline backend/services/services.go]: Shouldn't be there just a nil value?

File: backend/services/services.go [hunk 2]
```diff
@@ -51,42 +51,42 @@ func GetTweetsOfUserWithID(userID int64) ([]APIModel.Tweet, *appErrors.AppError)
...
 			Code: http.StatusNotFound,
 			Err:  errors.New("User with given ID was not found."),
 		}
 	}
 
-	APITweet, serviceError := convertDatabaseTweetToAPITweet(databaseTweet)
+	APITweet, serviceError := convertDatabaseTweetToAPITweet(&databaseTweet)
 
 	if serviceError != nil {
-		return APIModel.Tweet{}, serviceError
```
Comment (VirrageS) [inline backend/services/services.go]: Shouldn't be there just a nil value?

File: backend/services/services.go [hunk 3]
```diff
@@ -51,42 +51,42 @@ func GetTweetsOfUserWithID(userID int64) ([]APIModel.Tweet, *appErrors.AppError)
...
+func PostTweet(newTweet *APIModel.NewTweet) (*APIModel.Tweet, *appErrors.AppError) {
 	// TODO: reject if content is empty or when user submitted the same tweet more than once
 	databaseTweet := convertAPINewTweetToDatabaseTweet(newTweet)
 
-	addedTweet, databaseError := database.InsertTweet(databaseTweet)
+	addedTweet, databaseError := database.InsertTweet(*databaseTweet)
 
 	if databaseError != nil {
 		// for now its an unexpected error, but later on we'll probably need an error type switch here too
-		return APIModel.Tweet{}, appErrors.UnexpectedError
```
Comment (VirrageS) [inline backend/services/services.go]: Shouldn't be there just a nil value?

File: backend/services/services.go [hunk 4]
```diff
@@ -51,42 +51,42 @@ func GetTweetsOfUserWithID(userID int64) ([]APIModel.Tweet, *appErrors.AppError)
...
+		return &APIModel.Tweet{}, appErrors.UnexpectedError
 	}
 
-	APITweet, serviceError := convertDatabaseTweetToAPITweet(addedTweet)
+	APITweet, serviceError := convertDatabaseTweetToAPITweet(&addedTweet)
 
 	if serviceError != nil {
-		return APIModel.Tweet{}, serviceError
```
Comment (VirrageS) [inline backend/services/services.go]: Shouldn't be there just a nil value?

File: backend/services/services.go [hunk 5]
```diff
@@ -129,42 +129,42 @@ func GetUsers() ([]APIModel.User, *appErrors.AppError) {
...
 }
 
-func GetUser(userId int64) (APIModel.User, *appErrors.AppError) {
+func GetUser(userId int64) (*APIModel.User, *appErrors.AppError) {
 	databaseUser, databaseError := database.GetUserByID(userId)
 
 	if databaseError != nil {
 		// Maybe later on we'll need to add type switch here to check the type of error, because several things
 		// can go wrong when fetching data from database: not found, SQL error, db connection error etc
-		return APIModel.User{}, &appErrors.AppError{
```
Comment (VirrageS) [inline backend/services/services.go]: Shouldn't be there just a nil value?

File: backend/services/services.go [hunk 6]
```diff
@@ -129,42 +129,42 @@ func GetUsers() ([]APIModel.User, *appErrors.AppError) {
...
-func RegisterUser(newUserForm APIModel.NewUserForm) (APIModel.User, *appErrors.AppError) {
+func RegisterUser(newUserForm *APIModel.NewUserForm) (*APIModel.User, *appErrors.AppError) {
 	databaseUser := covertAPINewUserToDatabaseUser(newUserForm)
 
-	newUser, err := database.InsertUser(databaseUser)
+	newUser, err := database.InsertUser(*databaseUser)
 
 	if err != nil {
 		// again, one error only for now...
-		return APIModel.User{}, &appErrors.AppError{
```
Comment (VirrageS) [inline backend/services/services.go]: Shouldn't be there just a nil value?

File: backend/services/services.go [hunk 7]
```diff
@@ -227,14 +227,14 @@ func convertDatabaseTweetToAPITweet(tweet databaseModel.Tweet) (APIModel.Tweet,
 			"tweetID": tweetID,
 			"userID":  userID,
 		}).Error("Failed to convert database tweet to API tweet. User was not found in database.")
-		return APIModel.Tweet{}, appErrors.UnexpectedError
```
Comment (VirrageS) [inline backend/services/services.go]: Shouldn't be there just a nil value?

File: backend/middleware/token_authenticator.go [hunk 8]
```diff
@@ -40,12 +39,6 @@ func TokenAuthenticator(context *gin.Context) {
 			context.AbortWithError(http.StatusUnauthorized, errors.New("Invalid authentication token."))
 			return
 		}
-
-		if unexpired := claims.VerifyExpiresAt(time.Now().Unix(), true); !unexpired {
```
Comment (VirrageS) [inline backend/middleware/token_authenticator.go]: Why is it not checked now?

File: backend/services/services.go [hunk 9]
```diff
@@ -179,21 +179,21 @@ func LoginUser(loginForm APIModel.LoginForm) (*APIModel.LoginResponse, *appError
...
+	token, serviceError := createTokenForUser(&databaseUser)
 	if serviceError != nil {
 		return nil, serviceError
 	}
 
-	apiUser := convertDatabaseUserToAPIUser(databaseUser)
+	apiUser := convertDatabaseUserToAPIUser(&databaseUser)
 	response := &APIModel.LoginResponse{
 		AuthToken: token,
-		User:      apiUser,
```
Comment (VirrageS) [inline backend/services/services.go]: I think that this struct should have `*User` in definition.

File: backend/services/services.go [hunk 10]
```diff
@@ -227,14 +227,14 @@ func convertDatabaseTweetToAPITweet(tweet databaseModel.Tweet) (APIModel.Tweet,
 			"tweetID": tweetID,
 			"userID":  userID,
 		}).Error("Failed to convert database tweet to API tweet. User was not found in database.")
-		return APIModel.Tweet{}, appErrors.UnexpectedError
+		return &APIModel.Tweet{}, appErrors.UnexpectedError
 	}
 
-	APIAuthorFullData := convertDatabaseUserToAPIUser(authorFullData)
```
Comment (VirrageS) [inline backend/services/services.go]: Why no just `author` instead of `authorFullData`?

File: backend/services/services.go [hunk 11]
```diff
@@ -227,14 +227,14 @@ func convertDatabaseTweetToAPITweet(tweet databaseModel.Tweet) (APIModel.Tweet,
...
+	APIAuthorFullData := convertDatabaseUserToAPIUser(&authorFullData)
 
-	APITweet := APIModel.Tweet{
+	APITweet := &APIModel.Tweet{
 		ID:        tweetID,
-		Author:    APIAuthorFullData,
```
Comment (VirrageS) [inline backend/services/services.go]: I think that this struct should have `*Author` in definition.
