### PR TITLE
Fix bugs

### LINKED ISSUE #165: `null` response when returning 0 sized array
When hitting `/home_feed` when user has not created any tweet it will result in `null` response instead of `[]` as expected. It is because in **json.Marshal** `empty array != nil slice`:
```
var tweets []*model.Tweet
assert(tweets == nil) // true
```

proper approach to this problem is to initialize variable:
```
tweets := []*model.Tweets{} // not sure about this but should work
```
or 
```
tweets := make([]*model.Tweets, 0)
```

And this problem is not just in `/home_feed`!

### LINKED ISSUE #167: Response of `/login` does not contain `follower_count` field
After login of user response (returned user) does not have `follower_count` field.

It is probably because:
```
	response := &model.LoginResponse{
		AuthToken:    authToken,
		RefreshToken: refreshToken,
		User: &model.PublicUser{
			ID:        user.ID,
			Username:  user.Username,
			Name:      user.Name,
			AvatarUrl: user.AvatarUrl.String,
			Following: user.Following,
		},
	}
```
does not set `FollowerCount` field.

### LINKED ISSUE #168: Typos in backend documentation
I have found few typos in `api.yaml` file:

- `/user/{user_id}/following:` -> `/users/{user_id}/followees:`
- `/user/{user_id}/followers:` -> `/users/{user_id}/followers:`
- `/user/{user_id}/unfollow:` -> `/users/{user_id}/unfollow:`

### PR DESCRIPTION
**Pull request by Prytu**
Closes #165 
Closes #167 
Closes #168 

also is I think it fixes backend part of #166

### CODE REVIEW

**Comment by Prytu** [comment]
Made a small update to tests so they look a bit more like given/when/then schema: http://martinfowler.com/bliki/GivenWhenThen.html

File: backend/database/tweet.go [hunk 1]
```diff
@@ -25,8 +25,8 @@ func NewTweetDB(databaseConnection *sql.DB, cache cache.CacheProvider) *TweetDB
 }
 
 func (db *TweetDB) GetTweets(requestingUserID int64) ([]*model.Tweet, error) {
-	var tweets []*model.Tweet
-	if exists, _ := db.cache.Get("tweets", &tweets); exists {
+	tweets := make([]*model.Tweet, 0)
+	if exists, _ := db.cache.GetWithFields(cache.Fields{"tweets", "requser", requestingUserID}, &tweets); exists {
```
Comment (VirrageS) [inline backend/database/tweet.go]: "requser" is unnecessary.

File: backend/tests/integration/server_test.go [hunk 2]
```diff
@@ -144,12 +150,13 @@ var _ = Describe("ServerTest", func() {
...
+
 			router.ServeHTTP(w, req)
 
 			var loginResponse model.LoginResponse
 			err := json.Unmarshal(w.Body.Bytes(), &loginResponse)
-			Expect(err).NotTo(HaveOccurred())
 
+			Expect(err).NotTo(HaveOccurred())
 			Expect(w.Code).To(Equal(http.StatusOK))
 			Expect(loginResponse.User).To(Equal(loggedUser))
```
Comment (VirrageS) [inline backend/tests/integration/server_test.go]: Why didn't this line fail before?

File: backend/database/tweet.go (hunk 1 above)
Comment (Prytu) [inline backend/database/tweet.go]: you sure? I'd leave it so that its consistent with the rest of the code, what do you think?

Comment (VirrageS) [inline backend/database/tweet.go]: What you mean "rest of code"?

Comment (Prytu) [inline backend/database/tweet.go]: In almost all other places when I use cache, I add the info about the 'requesting user'. Here I add that info too, but the prefix 'requser' is not necessary. But I thought that it would be good to have it consistent with other places where we use cache and use the 'requser' prefix.
Unless you meant that we don't need the 'requser' anywhere. Then its right that we don't need but I think this makes code much easier to understand.

Comment (VirrageS) [inline backend/database/tweet.go]: I meant everywhere. Sorry, I haven't pointed it out.
