### PR TITLE
Fix panic and move users tweets endpoint

### LINKED ISSUE #207: Panic in backend when accessing `/home_feed`
Stack:
```
runtime error: index out of range
/usr/local/Cellar/go/1.7/libexec/src/runtime/panic.go:458 (0x2a473)
	gopanic: reflectcall(nil, unsafe.Pointer(d.fn), deferArgs(d), uint32(d.siz), uint32(d.siz))
/usr/local/Cellar/go/1.7/libexec/src/runtime/panic.go:27 (0x28d4d)
	panicindex: panic(indexError)
/Users/virrages/.go/src/github.com/VirrageS/chirp/backend/storage/tweet.go:206 (0x24eee6)
	(*TweetStorage).getTweetsByIDs: tweetsIDs[i] = tweetsIDs[len(tweetsIDs)-1]
/Users/virrages/.go/src/github.com/VirrageS/chirp/backend/storage/tweet.go:46 (0x24bb12)
	(*TweetStorage).GetUsersTweets: tweets, err := s.getTweetsByIDs(tweetsIDs, requestingUserID)
<autogenerated>:29 (0x255032)
/Users/virrages/.go/src/github.com/VirrageS/chirp/backend/service/service.go:26 (0x24a61b)
	(*Service).GetTweetsOfUserWithID: tweets, err := service.storage.GetUsersTweets(userID, requestingUserID)
/Users/virrages/.go/src/github.com/VirrageS/chirp/backend/api/tweet.go:153 (0x248c36)
	(*API).HomeFeed: tweets, err := api.service.GetTweetsOfUserWithID(requestingUserID, requestingUserID)
/Users/virrages/.go/src/github.com/VirrageS/chirp/backend/server/setup.go:72 (0x70739)
	(APIProvider).HomeFeed-fm: homeFeed.GET("", api.HomeFeed)
/Users/virrages/.go/src/gopkg.in/gin-gonic/gin.v1/context.go:97 (0x233e6a)
	(*Context).Next: c.handlers[c.index](c)
/Users/virrages/.go/src/github.com/VirrageS/chirp/backend/middleware/token_authenticator.go:24 (0x24a383)
	TokenAuthenticator.func1: context.Next()
/Users/virrages/.go/src/gopkg.in/gin-gonic/gin.v1/context.go:97 (0x233e6a)
	(*Context).Next: c.handlers[c.index](c)
/Users/virrages/.go/src/github.com/VirrageS/chirp/backend/middleware/error_handler.go:7 (0x249f10)
	ErrorHandler.func1: context.Next()
/Users/virrages/.go/src/gopkg.in/gin-gonic/gin.v1/context.go:97 (0x233e6a)
	(*Context).Next: c.handlers[c.index](c)
/Users/virrages/.go/src/gopkg.in/gin-gonic/gin.v1/recovery.go:45 (0x2438aa)
	RecoveryWithWriter.func1: c.Next()
/Users/virrages/.go/src/gopkg.in/gin-gonic/gin.v1/context.go:97 (0x233e6a)
	(*Context).Next: c.handlers[c.index](c)
/Users/virrages/.go/src/gopkg.in/gin-gonic/gin.v1/logger.go:63 (0x242a17)
	LoggerWithWriter.func1: c.Next()
/Users/virrages/.go/src/gopkg.in/gin-gonic/gin.v1/context.go:97 (0x233e6a)
	(*Context).Next: c.handlers[c.index](c)
/Users/virrages/.go/src/gopkg.in/gin-gonic/gin.v1/gin.go:284 (0x239f6e)
	(*Engine).handleHTTPRequest: context.Next()
/Users/virrages/.go/src/gopkg.in/gin-gonic/gin.v1/gin.go:265 (0x239850)
	(*Engine).ServeHTTP: engine.handleHTTPRequest(c)
/usr/local/Cellar/go/1.7/libexec/src/net/http/server.go:2202 (0x29c8bd)
	serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
/usr/local/Cellar/go/1.7/libexec/src/net/http/server.go:1579 (0x299227)
	(*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
/usr/local/Cellar/go/1.7/libexec/src/runtime/asm_amd64.s:2086 (0x59031)
	goexit: BYTE	$0x90	// NOP
```

### LINKED ISSUE #213: Rename `/tweets?userID=:id` endpoint to `/users/:id/tweets`

### PR DESCRIPTION
**Pull request by Prytu**
fixes #213
fixes #207

### CODE REVIEW

File: backend/storage/user.go [hunk 1]
```diff
@@ -262,36 +283,43 @@ func (s *UserStorage) collectPublicUserData(user *model.PublicUser, requestingUs
...
+			usersIDs[notInCacheCount] = id
+			notInCacheCount++
 		}
 	}
 
 	// get users that are not in cache from database
-	if len(usersIDs) > 0 {
-		dbFollowers, err := s.userDAO.GetPublicUsersByIDs(usersIDs)
+	if notInCacheCount > 0 {
+		dbFollowers, err := s.userDAO.GetPublicUsersByIDs(usersIDs[:notInCacheCount])
```
Comment (VirrageS) [inline backend/storage/user.go]: `dbFollowers` -> `dbUsers`

File: backend/api.yaml [hunk 2]
```diff
@@ -922,16 +862,16 @@ paths:
...
-          description: An array of tweet that represents users timeline.
+          description: An array of tweets that fulfill given cirteria.
           schema:
             type: array
             items:
               $ref: '#/definitions/Tweet'
-        404:
-          description: User with given ID does not exist.
+        400:
+          description: One of the query parameters is not supported.
```
Comment (VirrageS) [inline backend/api.yaml]: `When given user_id in url is invalid.`

File: backend/api.yaml [hunk 3]
```diff
@@ -906,9 +844,11 @@ paths:
                 type: string
                 description: Error message.
 
-  /user_timeline/{user_id}:
+  /users/{user_id}/tweets:
```
Comment (VirrageS) [inline backend/api.yaml]: - This also returns `401` or something when not authorized.
 - And should return `404` if user_id is valid but was not found. Not sure if this error is counted as `400` (bad request) but I think it should return `404` (if this is not true also in other endpoints could you create issue to change this in other PR? it is not critical though)
